[package]
authors = ["Bryan Maynard <bsgbryan@gmail.com>"]
name = "parsicle"
version = "0.1.0"
edition = "2024"
description = "A little tool for parsing articles from the web and extracting useful data from them"
license-file = "LICENSE"
repository = "https://github.com/bsgbryan/parsicle"

[dependencies]
article_scraper = "2.1.2"
chrono = "0.4.41"
comrak = "0.39.0"
html2md = "0.2.15"
reqwest = "0.12.20"
scraper = "0.23.1"
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread"] }
url = "2.5.4"
